export enum ErrorCode {
  // --- AUTH & ACCOUNT ---
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_UNSET = 'EMAIL_UNSET',
  PENDING_PASSWORD = 'PENDING_PASSWORD',

  // --- TOKEN ---
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',

  // --- PERMISSIONS ---
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // --- INPUT & VALIDATION ---
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_FILE = 'INVALID_FILE',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // --- SERVER ---
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // --- STORE & MEMBER ---
  STORE_NOT_FOUND = 'STORE_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',

  // --- PRODUCT & CATEGORY ---
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // --- IMAGE & MEDIA ---
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
}
